# Generated by Django 5.0 on 2023-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('volunteer', 'Volunteer'), ('senior_citizen', 'Senior Citizen')], max_length=20),
        ),
    ]
