# Generated by Django 5.0 on 2023-12-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0002_userprofile_age_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
