# Generated by Django 5.0 on 2023-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0005_remove_userprofile_id_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.AutoField(default=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
