# Generated by Django 5.0 on 2023-12-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0005_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='type',
        ),
    ]
