# Generated by Django 5.0 on 2023-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0006_alter_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
