# Generated by Django 5.0 on 2023-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
