# Generated by Django 5.0.1 on 2024-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userx',
            old_name='id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userx',
            name='type',
            field=models.CharField(blank=True, choices=[('volunteer', 'Volunteer'), ('senior_citizen', 'Senior Citizen')], max_length=20),
        ),
    ]
