# Generated by Django 5.0.1 on 2024-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0002_rename_id_userx_user_userx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userx',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userx',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
