# Generated by Django 5.0.1 on 2024-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='exit', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
