# Generated by Django 5.0.1 on 2024-01-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0010_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
