# Generated by Django 5.0.1 on 2024-01-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0012_appointment_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
        migrations.AddField(
            model_name='appointment',
            name='senior_citizen_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='volunteer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='senior_citizen_username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='volunteer_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
