# Generated by Django 5.0.1 on 2024-02-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overall1', '0014_appointment_created_at_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='senior_citizen_username',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='volunteer_username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='senior_citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_citizen_appointments', to='overall1.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_appointments', to='overall1.userprofile'),
        ),
    ]
